### ISSUE TITLE
Just thanks

### ISSUE THREAD

**Issue by Eloren1** [ArnewGonz/Unity-HDRP-PSX-Effects#1]
Who would have thought that the HDRP would be used for this?

![image](https://github.com/ArnewGonz/Unity-HDRP-PSX-Effects/assets/46666053/7db4f537-83ef-460f-9018-24c976354ed4)

**Comment by ArnewGonz** [comment]
OMG THIS IS SO COOL!!! I'm so happy to see that it's useful!!

PD: Sorry for the late reply :((
